In [1]:
import gym
import numpy as np
import tensorflow as tf

/home/scratch.ftse_ampere-info/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
env.observation_space

Discrete(16)

In [4]:
env.action_space

Discrete(4)

In [23]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []

for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j += 1
        # Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [24]:
print(Q)
print("Score over time: " +  str(sum(rList)/num_episodes))

[[2.18046763e-01 3.48703212e-03 5.56899603e-03 3.98464404e-03]
 [6.57131018e-04 6.16688688e-04 2.22690645e-04 1.51579768e-01]
 [2.02215606e-01 8.77893599e-04 7.40772315e-04 2.53720550e-03]
 [1.67230807e-04 5.46319413e-04 4.87321453e-04 2.47911602e-03]
 [3.81115668e-01 5.62215438e-04 1.24205390e-05 8.31473932e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.41680537e-04 1.23104728e-04 1.81796738e-01 8.09510070e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.45212505e-05 2.65926935e-04 4.63789833e-01]
 [0.00000000e+00 4.66519892e-01 1.09058552e-03 2.92284501e-03]
 [3.29510226e-01 3.50121692e-04 1.50565121e-05 5.44187547e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.37892275e-02 5.31376665e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 8.76285124e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [32]:
print(env.step.__doc__)

s = env.reset()
for i in range(200):
    env.render()
    a = np.argmax(Q[s, :])
    s,r,d,_ = env.step(a)
    print(s, r, d)
    if d == True:
        break
        
env.render()
print("Steps = {}".format(i))

None

SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
4 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
9 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
8 0.0 False
  (Down)
SFFF
FHFH
FFFH
HFFG
9 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
13 0.0 False
  (Down)
SFFF
FHFH
FFFH
HFFG
13 0.0 False
  (Right)
SFFF
FHFH
FFFH
HFFG
14 0.0 False
  (Right)
SFFF
FHFH
FFFH
HFFG
10 0.0 False
  (Up)
SFFF
FHFH
FFFH
HFFG
9 0.0 False
  (Left)
SFFF
FHFH
FFFH
HFFG
10 0.0 False
  (Down)
SFFF
FHFH
FFFH
HFFG
6 0

In [31]:
s

15

In [12]:
np.random.randn(1,env.action_space.n)

array([[ 0.09718389, -0.56868437,  1.27956972,  1.16444559]])

In [18]:
env.observation_space

Discrete(16)

In [20]:
env.render()

  (Right)
SFFF
FHFH
FFFH
HFFG


In [21]:
env.reset()

0

In [22]:
env.render()


SFFF
FHFH
FFFH
HFFG
